from __future__ import annotations

import random

from src.sources.base_source import BaseSource
from src.tools.base import ToolResult

# 50+ 条预定义 AI Engineer 校招岗位数据
MOCK_JOBS = [
    {
        "title": "AI算法工程师（2026届校招）",
        "company": "字节跳动",
        "location": "北京",
        "salary": "25k-45k",
        "tech_tags": ["PyTorch", "Transformer", "NLP", "大模型"],
        "requirements": "计算机/人工智能相关专业硕士及以上，熟悉深度学习框架，有大模型训练或微调经验优先",
        "source": "mock",
        "job_url": "https://jobs.bytedance.com/mock/1",
        "description": "负责大语言模型相关算法研究与工程落地，参与模型训练、微调和推理优化工作。",
    },
    {
        "title": "大模型算法工程师（校招）",
        "company": "阿里巴巴",
        "location": "杭州",
        "salary": "25k-40k",
        "tech_tags": ["PyTorch", "LLM", "RLHF", "分布式训练"],
        "requirements": "985/211硕士及以上，熟悉Transformer架构，有NLP/大模型相关项目经验",
        "source": "mock",
        "job_url": "https://talent.alibaba.com/mock/2",
        "description": "参与通义千问大模型研发，负责预训练数据清洗、SFT、RLHF等关键环节。",
    },
    {
        "title": "机器学习工程师（2026校招）",
        "company": "腾讯",
        "location": "深圳",
        "salary": "22k-38k",
        "tech_tags": ["TensorFlow", "推荐系统", "特征工程", "XGBoost"],
        "requirements": "计算机/统计学相关专业，熟悉机器学习常用算法，有推荐系统经验优先",
        "source": "mock",
        "job_url": "https://join.qq.com/mock/3",
        "description": "负责腾讯视频/微信推荐系统的算法优化，提升推荐精准度和用户体验。",
    },
    {
        "title": "LLM应用开发工程师（校招）",
        "company": "百度",
        "location": "北京",
        "salary": "20k-35k",
        "tech_tags": ["LangChain", "RAG", "Prompt Engineering", "Python"],
        "requirements": "熟悉大模型应用开发，有RAG/Agent系统搭建经验，Python熟练",
        "source": "mock",
        "job_url": "https://talent.baidu.com/mock/4",
        "description": "参与文心一言大模型应用层开发，构建RAG系统和AI Agent应用。",
    },
    {
        "title": "计算机视觉算法工程师（校招）",
        "company": "华为",
        "location": "深圳",
        "salary": "20k-35k",
        "tech_tags": ["PyTorch", "CV", "目标检测", "图像分割"],
        "requirements": "计算机视觉相关方向硕士，熟悉CNN/ViT等模型，有论文发表优先",
        "source": "mock",
        "job_url": "https://career.huawei.com/mock/5",
        "description": "负责自动驾驶/手机摄影中的视觉算法研发，包括目标检测、语义分割等。",
    },
    {
        "title": "NLP算法工程师（2026届）",
        "company": "美团",
        "location": "北京",
        "salary": "22k-38k",
        "tech_tags": ["NLP", "BERT", "文本分类", "知识图谱"],
        "requirements": "NLP方向硕士及以上，熟悉预训练模型微调，有知识图谱经验优先",
        "source": "mock",
        "job_url": "https://zhaopin.meituan.com/mock/6",
        "description": "负责美团搜索和推荐的NLP算法优化，包括意图理解、实体识别等。",
    },
    {
        "title": "深度学习推理优化工程师（校招）",
        "company": "NVIDIA",
        "location": "上海",
        "salary": "30k-50k",
        "tech_tags": ["CUDA", "TensorRT", "ONNX", "模型压缩"],
        "requirements": "计算机相关专业硕士，熟悉GPU编程和深度学习推理优化",
        "source": "mock",
        "job_url": "https://nvidia.com/mock/7",
        "description": "负责TensorRT推理引擎开发，优化大模型在GPU上的推理性能。",
    },
    {
        "title": "AI平台工程师（校招）",
        "company": "蚂蚁集团",
        "location": "杭州",
        "salary": "22k-38k",
        "tech_tags": ["MLOps", "Kubernetes", "Docker", "Python"],
        "requirements": "计算机相关专业，熟悉K8s和Docker，了解机器学习全流程",
        "source": "mock",
        "job_url": "https://antgroup.com/mock/8",
        "description": "负责蚂蚁AI平台的开发维护，为算法团队提供高效的模型训练和部署平台。",
    },
    {
        "title": "多模态算法工程师（校招）",
        "company": "快手",
        "location": "北京",
        "salary": "25k-42k",
        "tech_tags": ["多模态", "CLIP", "Diffusion", "视频理解"],
        "requirements": "多模态/视频理解方向硕士，熟悉ViT/Diffusion模型",
        "source": "mock",
        "job_url": "https://kuaishou.com/mock/9",
        "description": "负责快手多模态内容理解和生成算法研发，包括视频理解和图像生成。",
    },
    {
        "title": "语音算法工程师（2026校招）",
        "company": "小米",
        "location": "北京",
        "salary": "20k-35k",
        "tech_tags": ["语音识别", "TTS", "PyTorch", "Kaldi"],
        "requirements": "语音处理方向硕士，熟悉ASR/TTS算法，有Kaldi/ESPNet经验",
        "source": "mock",
        "job_url": "https://hr.xiaomi.com/mock/10",
        "description": "负责小爱同学的语音识别和语音合成算法研发。",
    },
    {
        "title": "搜索算法工程师（校招）",
        "company": "京东",
        "location": "北京",
        "salary": "20k-35k",
        "tech_tags": ["搜索排序", "NLP", "向量检索", "ElasticSearch"],
        "requirements": "信息检索/机器学习方向硕士，熟悉搜索排序算法",
        "source": "mock",
        "job_url": "https://zhaopin.jd.com/mock/11",
        "description": "负责京东商品搜索的排序算法优化，提升搜索准确性和用户体验。",
    },
    {
        "title": "自动驾驶感知算法工程师（校招）",
        "company": "小鹏汽车",
        "location": "广州",
        "salary": "25k-40k",
        "tech_tags": ["3D目标检测", "LiDAR", "BEV", "自动驾驶"],
        "requirements": "自动驾驶/计算机视觉方向硕士，熟悉3D感知算法",
        "source": "mock",
        "job_url": "https://xiaopeng.com/mock/12",
        "description": "负责自动驾驶感知系统算法研发，包括3D目标检测和多传感器融合。",
    },
    {
        "title": "强化学习算法工程师（校招）",
        "company": "网易",
        "location": "杭州",
        "salary": "20k-35k",
        "tech_tags": ["强化学习", "RLHF", "PPO", "游戏AI"],
        "requirements": "强化学习方向硕士，熟悉PPO/SAC等算法，有游戏AI经验优先",
        "source": "mock",
        "job_url": "https://hr.163.com/mock/13",
        "description": "负责网易游戏AI算法研发，包括NPC行为决策和游戏平衡性优化。",
    },
    {
        "title": "数据科学家（校招）",
        "company": "拼多多",
        "location": "上海",
        "salary": "25k-40k",
        "tech_tags": ["数据分析", "SQL", "Python", "A/B测试"],
        "requirements": "统计学/数学/计算机相关专业，熟练SQL和Python，有数据分析经验",
        "source": "mock",
        "job_url": "https://pinduoduo.com/mock/14",
        "description": "负责拼多多业务数据分析，构建用户画像和推荐策略。",
    },
    {
        "title": "AI Agent开发工程师（校招）",
        "company": "月之暗面",
        "location": "北京",
        "salary": "25k-45k",
        "tech_tags": ["LangChain", "Agent", "RAG", "Tool Use"],
        "requirements": "熟悉大模型应用开发，有Agent/RAG系统开发经验，Python熟练",
        "source": "mock",
        "job_url": "https://moonshot.com/mock/15",
        "description": "负责Kimi AI Agent系统开发，构建多工具调用的智能助手。",
    },
    {
        "title": "大模型训练工程师（校招）",
        "company": "智谱AI",
        "location": "北京",
        "salary": "25k-45k",
        "tech_tags": ["分布式训练", "DeepSpeed", "Megatron", "CUDA"],
        "requirements": "计算机相关专业硕士，熟悉大模型分布式训练框架",
        "source": "mock",
        "job_url": "https://zhipuai.com/mock/16",
        "description": "负责GLM系列大模型的分布式训练优化，提升训练效率和稳定性。",
    },
    {
        "title": "推荐算法工程师（校招）",
        "company": "滴滴出行",
        "location": "北京",
        "salary": "22k-38k",
        "tech_tags": ["推荐系统", "深度学习", "特征工程", "排序模型"],
        "requirements": "机器学习/推荐系统方向硕士，熟悉深度学习推荐模型",
        "source": "mock",
        "job_url": "https://didiglobal.com/mock/17",
        "description": "负责滴滴派单和推荐系统的算法优化，提升匹配效率。",
    },
    {
        "title": "AIGC算法工程师（校招）",
        "company": "商汤科技",
        "location": "上海",
        "salary": "22k-40k",
        "tech_tags": ["Diffusion", "GAN", "图像生成", "Stable Diffusion"],
        "requirements": "计算机视觉/生成模型方向硕士，熟悉Diffusion/GAN",
        "source": "mock",
        "job_url": "https://sensetime.com/mock/18",
        "description": "负责AIGC图像和视频生成算法研发，参与大模型文生图系统开发。",
    },
    {
        "title": "知识图谱工程师（校招）",
        "company": "搜狗",
        "location": "北京",
        "salary": "18k-30k",
        "tech_tags": ["知识图谱", "NLP", "图数据库", "实体链接"],
        "requirements": "知识图谱/NLP方向硕士，熟悉Neo4j等图数据库",
        "source": "mock",
        "job_url": "https://sogou.com/mock/19",
        "description": "负责知识图谱构建和应用，支持搜索和问答系统的知识推理。",
    },
    {
        "title": "联邦学习算法工程师（校招）",
        "company": "微众银行",
        "location": "深圳",
        "salary": "20k-35k",
        "tech_tags": ["联邦学习", "隐私计算", "PyTorch", "密码学"],
        "requirements": "隐私计算/联邦学习方向硕士，熟悉FATE等框架",
        "source": "mock",
        "job_url": "https://webank.com/mock/20",
        "description": "负责联邦学习平台算法研发，在保护数据隐私的前提下实现联合建模。",
    },
    {
        "title": "大模型评测工程师（校招）",
        "company": "上海人工智能实验室",
        "location": "上海",
        "salary": "20k-35k",
        "tech_tags": ["大模型评测", "Benchmark", "Python", "数据分析"],
        "requirements": "计算机/NLP方向硕士，熟悉大模型评测方法和基准",
        "source": "mock",
        "job_url": "https://shlab.com/mock/21",
        "description": "负责构建和维护大模型评测体系，设计评测任务和指标。",
    },
    {
        "title": "机器学习平台工程师（校招）",
        "company": "B站",
        "location": "上海",
        "salary": "20k-35k",
        "tech_tags": ["MLOps", "Kubernetes", "特征平台", "Python"],
        "requirements": "计算机相关专业，熟悉K8s和机器学习工程化",
        "source": "mock",
        "job_url": "https://bilibili.com/mock/22",
        "description": "负责B站机器学习平台开发，提供模型训练、部署和监控的一站式服务。",
    },
    {
        "title": "对话系统算法工程师（校招）",
        "company": "科大讯飞",
        "location": "合肥",
        "salary": "18k-30k",
        "tech_tags": ["对话系统", "NLP", "LLM", "意图识别"],
        "requirements": "NLP/对话系统方向硕士，熟悉大模型和对话管理",
        "source": "mock",
        "job_url": "https://iflytek.com/mock/23",
        "description": "负责星火大模型的对话能力优化，包括意图理解和多轮对话管理。",
    },
    {
        "title": "图像算法工程师（2026届校招）",
        "company": "OPPO",
        "location": "深圳",
        "salary": "20k-35k",
        "tech_tags": ["图像处理", "计算摄影", "CV", "PyTorch"],
        "requirements": "计算机视觉/图像处理方向硕士，熟悉计算摄影算法",
        "source": "mock",
        "job_url": "https://oppo.com/mock/24",
        "description": "负责OPPO手机相机图像处理算法研发，包括降噪、HDR和人像美化。",
    },
    {
        "title": "风控算法工程师（校招）",
        "company": "陆金所",
        "location": "上海",
        "salary": "20k-35k",
        "tech_tags": ["风控模型", "机器学习", "特征工程", "XGBoost"],
        "requirements": "机器学习/统计方向硕士，有金融风控经验优先",
        "source": "mock",
        "job_url": "https://lu.com/mock/25",
        "description": "负责金融风控模型研发，构建反欺诈和信用评估系统。",
    },
    {
        "title": "自动驾驶规划控制算法工程师（校招）",
        "company": "理想汽车",
        "location": "北京",
        "salary": "25k-42k",
        "tech_tags": ["路径规划", "强化学习", "C++", "自动驾驶"],
        "requirements": "自动驾驶/控制工程方向硕士，熟悉路径规划算法",
        "source": "mock",
        "job_url": "https://lixiang.com/mock/26",
        "description": "负责理想汽车自动驾驶规划控制模块算法研发。",
    },
    {
        "title": "时序预测算法工程师（校招）",
        "company": "华为云",
        "location": "深圳",
        "salary": "20k-35k",
        "tech_tags": ["时序预测", "Transformer", " anomaly detection"],
        "requirements": "时序分析/机器学习方向硕士，熟悉时序预测模型",
        "source": "mock",
        "job_url": "https://huaweicloud.com/mock/27",
        "description": "负责云服务监控数据的时序预测和异常检测算法研发。",
    },
    {
        "title": "端侧AI算法工程师（校招）",
        "company": "高通",
        "location": "上海",
        "salary": "25k-40k",
        "tech_tags": ["模型量化", "端侧推理", "ONNX", "移动AI"],
        "requirements": "计算机相关专业硕士，熟悉模型量化和端侧部署",
        "source": "mock",
        "job_url": "https://qualcomm.com/mock/28",
        "description": "负责AI模型在移动端的部署优化，包括量化和剪枝。",
    },
    {
        "title": "AI安全工程师（校招）",
        "company": "奇安信",
        "location": "北京",
        "salary": "18k-30k",
        "tech_tags": ["AI安全", "对抗样本", "模型鲁棒性", "Python"],
        "requirements": "AI安全/对抗机器学习方向硕士，了解模型攻击和防御",
        "source": "mock",
        "job_url": "https://qianxin.com/mock/29",
        "description": "负责AI系统安全评估，研究对抗攻击和模型鲁棒性增强方法。",
    },
    {
        "title": "图神经网络算法工程师（校招）",
        "company": "腾讯",
        "location": "北京",
        "salary": "22k-38k",
        "tech_tags": ["GNN", "图神经网络", "推荐系统", "PyTorch Geometric"],
        "requirements": "图学习/推荐系统方向硕士，熟悉GNN模型",
        "source": "mock",
        "job_url": "https://join.qq.com/mock/30",
        "description": "负责社交网络和推荐系统中的图神经网络算法研发。",
    },
    {
        "title": "大模型对齐工程师（校招）",
        "company": "Anthropic",
        "location": "旧金山",
        "salary": "$120k-$180k",
        "tech_tags": ["RLHF", "Constitutional AI", "对齐", "安全"],
        "requirements": "AI安全/对齐方向博士优先，熟悉RLHF和AI安全研究",
        "source": "mock",
        "job_url": "https://anthropic.com/mock/31",
        "description": "参与大模型安全对齐研究，推进Constitutional AI方法。",
    },
    {
        "title": "多模态大模型工程师（校招）",
        "company": "MiniMax",
        "location": "上海",
        "salary": "25k-42k",
        "tech_tags": ["多模态", "LLM", "视觉语言模型", "Transformer"],
        "requirements": "多模态/大模型方向硕士，熟悉视觉语言模型",
        "source": "mock",
        "job_url": "https://minimax.com/mock/32",
        "description": "负责多模态大模型研发，打通文本、图像、语音的多模态理解。",
    },
    {
        "title": "机器人学习算法工程师（校招）",
        "company": "小米",
        "location": "北京",
        "salary": "25k-40k",
        "tech_tags": ["强化学习", "机器人", "Sim-to-Real", "模仿学习"],
        "requirements": "机器人/强化学习方向硕士，有机器人控制经验",
        "source": "mock",
        "job_url": "https://hr.xiaomi.com/mock/33",
        "description": "负责CyberOne人形机器人的学习算法研发。",
    },
    {
        "title": "搜索推荐算法工程师（校招）",
        "company": "小红书",
        "location": "上海",
        "salary": "22k-38k",
        "tech_tags": ["推荐系统", "NLP", "多模态", "深度学习"],
        "requirements": "推荐/NLP方向硕士，熟悉深度学习推荐模型",
        "source": "mock",
        "job_url": "https://xiaohongshu.com/mock/34",
        "description": "负责小红书内容推荐和搜索算法优化，提升内容分发效率。",
    },
    {
        "title": "AI基础设施工程师（校招）",
        "company": "字节跳动",
        "location": "上海",
        "salary": "25k-42k",
        "tech_tags": ["CUDA", "分布式系统", "RDMA", "深度学习框架"],
        "requirements": "系统/并行计算方向硕士，熟悉CUDA和分布式训练",
        "source": "mock",
        "job_url": "https://jobs.bytedance.com/mock/35",
        "description": "负责字节AI基础设施开发，优化大规模分布式训练性能。",
    },
    {
        "title": "对话式AI产品工程师（校招）",
        "company": "阿里巴巴",
        "location": "北京",
        "salary": "20k-35k",
        "tech_tags": ["LLM", "Agent", "Prompt Engineering", "产品思维"],
        "requirements": "对AI产品有热情，熟悉大模型应用开发，有产品实习经验优先",
        "source": "mock",
        "job_url": "https://talent.alibaba.com/mock/36",
        "description": "负责通义千问对话式AI产品开发，将LLM能力落地到实际产品。",
    },
    {
        "title": "视频理解算法工程师（校招）",
        "company": "字节跳动",
        "location": "上海",
        "salary": "25k-40k",
        "tech_tags": ["视频理解", "时序建模", "Transformer", "多模态"],
        "requirements": "视频理解方向硕士，熟悉视频特征提取和时序建模",
        "source": "mock",
        "job_url": "https://jobs.bytedance.com/mock/37",
        "description": "负责抖音视频内容理解算法，包括视频分类、标签提取等。",
    },
    {
        "title": "AI编译器工程师（校招）",
        "company": "华为",
        "location": "上海",
        "salary": "22k-38k",
        "tech_tags": ["TVM", "编译器", "算子优化", "C++"],
        "requirements": "编译器/系统方向硕士，熟悉TVM或MLIR",
        "source": "mock",
        "job_url": "https://career.huawei.com/mock/38",
        "description": "负责昇腾AI芯片的算子编译优化，提升模型推理性能。",
    },
    {
        "title": "数据挖掘工程师（校招）",
        "company": "美团",
        "location": "上海",
        "salary": "20k-35k",
        "tech_tags": ["数据挖掘", "Spark", "SQL", "Python"],
        "requirements": "数据挖掘/机器学习方向硕士，熟悉大数据处理",
        "source": "mock",
        "job_url": "https://zhaopin.meituan.com/mock/39",
        "description": "负责美团平台数据挖掘，构建用户画像和商家标签体系。",
    },
    {
        "title": "3D视觉算法工程师（校招）",
        "company": "大疆创新",
        "location": "深圳",
        "salary": "22k-38k",
        "tech_tags": ["3D重建", "SLAM", "点云处理", "NeRF"],
        "requirements": "3D视觉/SLAM方向硕士，熟悉多视图几何",
        "source": "mock",
        "job_url": "https://we.dji.com/mock/40",
        "description": "负责大疆无人机3D感知和建图算法研发。",
    },
    {
        "title": "语音大模型工程师（校招）",
        "company": "字节跳动",
        "location": "北京",
        "salary": "25k-40k",
        "tech_tags": ["语音大模型", "ASR", "TTS", "Transformer"],
        "requirements": "语音/AI方向硕士，熟悉语音大模型训练",
        "source": "mock",
        "job_url": "https://jobs.bytedance.com/mock/41",
        "description": "负责豆包语音大模型研发，实现端到端的语音理解和生成。",
    },
    {
        "title": "因果推断算法工程师（校招）",
        "company": "快手",
        "location": "杭州",
        "salary": "22k-38k",
        "tech_tags": ["因果推断", "A/B测试", "Python", "统计学"],
        "requirements": "因果推断/统计学方向硕士，熟悉因果推断方法",
        "source": "mock",
        "job_url": "https://kuaishou.com/mock/42",
        "description": "负责快手广告和推荐的因果推断分析，优化A/B测试框架。",
    },
    {
        "title": "AI for Science工程师（校招）",
        "company": "深势科技",
        "location": "北京",
        "salary": "22k-40k",
        "tech_tags": ["AI4Science", "分子模拟", "图神经网络", "PyTorch"],
        "requirements": "计算化学/物理/AI方向硕士，有AI4Science经验优先",
        "source": "mock",
        "job_url": "https://dp.tech/mock/43",
        "description": "负责AI驱动的新药研发和材料设计算法开发。",
    },
    {
        "title": "大模型推理服务工程师（校招）",
        "company": "百度",
        "location": "上海",
        "salary": "20k-35k",
        "tech_tags": ["vLLM", "推理服务", "Kubernetes", "Python"],
        "requirements": "系统/ML方向硕士，熟悉大模型推理框架和部署",
        "source": "mock",
        "job_url": "https://talent.baidu.com/mock/44",
        "description": "负责文心一言大模型推理服务优化，提升吞吐和降低延迟。",
    },
    {
        "title": "金融NLP算法工程师（校招）",
        "company": "蚂蚁集团",
        "location": "上海",
        "salary": "22k-38k",
        "tech_tags": ["NLP", "LLM", "金融科技", "文本分析"],
        "requirements": "NLP方向硕士，对金融领域有了解，有LLM应用经验",
        "source": "mock",
        "job_url": "https://antgroup.com/mock/45",
        "description": "负责蚂蚁金融NLP系统开发，包括智能客服和风控文本分析。",
    },
    {
        "title": "具身智能算法工程师（校招）",
        "company": "银河通用机器人",
        "location": "北京",
        "salary": "25k-45k",
        "tech_tags": ["具身智能", "强化学习", "机器人操控", "大模型"],
        "requirements": "机器人/AI方向硕士/博士，熟悉具身智能研究前沿",
        "source": "mock",
        "job_url": "https://galbot.com/mock/46",
        "description": "负责具身智能机器人算法研发，实现通用机器人操控能力。",
    },
    {
        "title": "模型压缩与加速工程师（校招）",
        "company": "商汤科技",
        "location": "北京",
        "salary": "20k-35k",
        "tech_tags": ["模型压缩", "知识蒸馏", "剪枝", "量化"],
        "requirements": "模型优化方向硕士，熟悉剪枝、量化、蒸馏技术",
        "source": "mock",
        "job_url": "https://sensetime.com/mock/47",
        "description": "负责大模型压缩和加速技术研发，降低推理成本。",
    },
    {
        "title": "AI交互设计工程师（校招）",
        "company": "网易",
        "location": "广州",
        "salary": "18k-30k",
        "tech_tags": ["对话设计", "Prompt Engineering", "UX", "LLM"],
        "requirements": "人机交互/AI方向，有对话系统设计经验，了解LLM能力边界",
        "source": "mock",
        "job_url": "https://hr.163.com/mock/48",
        "description": "负责网易有道AI产品的交互设计和Prompt优化。",
    },
    {
        "title": "RLHF工程师（校招）",
        "company": "阶跃星辰",
        "location": "上海",
        "salary": "25k-42k",
        "tech_tags": ["RLHF", "PPO", "奖励模型", "大模型对齐"],
        "requirements": "强化学习/大模型方向硕士，熟悉RLHF流程",
        "source": "mock",
        "job_url": "https://stepfun.com/mock/49",
        "description": "负责Step系列大模型的RLHF对齐训练，提升模型安全性。",
    },
    {
        "title": "AI全栈工程师（校招）",
        "company": "零一万物",
        "location": "北京",
        "salary": "22k-38k",
        "tech_tags": ["全栈", "Python", "React", "LLM应用"],
        "requirements": "全栈开发能力，熟悉AI应用开发，有Web开发经验",
        "source": "mock",
        "job_url": "https://01.ai/mock/50",
        "description": "负责Yi大模型全栈应用开发，从模型API到前端界面。",
    },
    {
        "title": "异常检测算法工程师（校招）",
        "company": "拼多多",
        "location": "北京",
        "salary": "22k-38k",
        "tech_tags": ["异常检测", "时序分析", "无监督学习", "Python"],
        "requirements": "异常检测/机器学习方向硕士，熟悉时序异常检测方法",
        "source": "mock",
        "job_url": "https://pinduoduo.com/mock/51",
        "description": "负责拼多多业务系统异常检测，保障平台稳定性。",
    },
    {
        "title": "AI芯片软件工程师（校招）",
        "company": "寒武纪",
        "location": "北京",
        "salary": "22k-38k",
        "tech_tags": ["AI芯片", "CUDA", "算子开发", "C++"],
        "requirements": "计算机体系结构方向硕士，熟悉GPU/AI芯片编程",
        "source": "mock",
        "job_url": "https://cambricon.com/mock/52",
        "description": "负责寒武纪AI芯片的算子库开发和性能优化。",
    },
]


class MockSource(BaseSource):
    """模拟数据源 - 50+ 条预定义 AI Engineer 校招岗位"""

    name = "mock"
    priority = 99  # 最低优先级

    def build_query(self, keywords: list[str]) -> str:
        return " ".join(keywords)

    async def search(self, query: str, page: int = 1) -> ToolResult:
        """返回模拟数据，支持基于关键词的简单过滤"""
        results = MOCK_JOBS.copy()
        # 简单关键词过滤
        if query:
            query_lower = query.lower()
            keywords = query_lower.split()
            filtered = []
            for job in results:
                text = f"{job['title']} {job.get('description', '')} {' '.join(job.get('tech_tags', []))}".lower()
                if any(kw in text for kw in keywords):
                    filtered.append(job)
            if filtered:
                results = filtered

        # 模拟分页，每页20条
        start = (page - 1) * 20
        page_results = results[start : start + 20]

        # 添加随机性，模拟每次搜索结果不同
        if len(page_results) > 10:
            page_results = random.sample(page_results, min(len(page_results), 15))

        return ToolResult(success=True, data=page_results, source=self.name)
